name: Bug Report
description: File a bug report
title: "[Bug]"
labels: [ "bug" ]
assignees:
  - Matteas-Eden
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: the-issue
    attributes:
      label: What's the issue?
      description: Tell me everything you can about the bug.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: dropdown
      id: severity-level
      attributes:
        label: How severe is this bug?
        description: Not all bugs are made equal.
        multiple: false
        options:
          - Critical
          - Moderate
          - Low
      validations:
        required: true
  - type: textarea
      id: anything-else
      attributes:
        label: Is there anything else?
        description: For example, extra information that doesn't fit above.
